### PR TITLE
Fixed LGTM warnings

### PR DESCRIPTION
**Pull request by ffangliu**
Fixed LGTM warnings

### CODE REVIEW

**Comment by dgasmith** [comment]
Cool! Glad you like LGTM.

**Comment by ffangliu** [comment]
Yea, it's really a useful tool. Thanks for recommending.

**Comment by ffangliu** [comment]
This pull request **introduces 1 alert** and **fixes 3** when merging 3c04900c956b435888fdc97747e72682857fe38b into 069560c6d0b610c8cae9a89102b31e2e956de0ce - [view on LGTM.com](https://lgtm.com/projects/g/hjkgrp/MultirefPredict/rev/pr-f89e3e8c26c0e45080bf8defef98328ca78b1267)

**new alerts:**

* 1 for Unused import

**fixed alerts:**

* 2 for Unused import
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ffangliu** [comment]
This pull request **fixes 3 alerts** when merging df78d3a38d56b26e11c1dfa14f86475680c19367 into 069560c6d0b610c8cae9a89102b31e2e956de0ce - [view on LGTM.com](https://lgtm.com/projects/g/hjkgrp/MultirefPredict/rev/pr-aa5db4715d274ad6b439c5be8d1040dff1fc5993)

**fixed alerts:**

* 2 for Unused import
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
